# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feb1861f0c6d8d6cc1f95f171b5b5ead2694579396d8766b3ff92f47f6ab83648dc28a9099d06d2e73e1fc08ce3eea431af18fdbc1aec5c38cb345b60764d61f

test:
  secret_key_base: 3fdc0ea4294ad8f7882e086e22b12864caf5d9be63b67b0f74b88e9f052584cfee194c292822a6670a197dfd10c00df324007c13af2429f9f7fa6dcffd2f5e56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
